import type { Metadata } from "next";
import localFont from "next/font/local";
import { Satisfy, Poppins } from 'next/font/google'
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const satisfy_font = Satisfy({
  weight: '400',
  subsets: ['latin'],
  // display: 'swap',
  variable: '--font-satisfy',
})
const poppins_font = Poppins({
  weight: '400',
  subsets: ['latin'],
  // display: 'swap',
  variable: '--font-poppins',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${satisfy_font.variable} ${poppins_font.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
